# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://github.com/crmne/cookiecutter-modern-datascience
fail_fast: true
files: ^bigbio/biodatasets/
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-case-conflict
        -   id: debug-statements
        -   id: detect-private-key
        -   id: check-merge-conflict
        -   id: check-added-large-files
    # -   repo: https://github.com/myint/autoflake
    #     rev: v1.7.6
    #     hooks:
    #     -   id: autoflake
    #         args:
    #           - --in-place
    #           - --remove-duplicate-keys
    #           - --remove-unused-variables
    #           - --remove-all-unused-imports
    #           - --expand-star-imports
    -   repo: https://github.com/PyCQA/flake8
        rev: 5.0.4
        hooks:
        -   id: flake8
            args:
                - --max-line-length
                - '119'
    -   repo: https://github.com/PyCQA/isort
        rev: 5.10.1
        hooks:
        -   id: isort
            args:
              - --profile
              - black
    -   repo: https://github.com/ambv/black
        rev: 22.10.0
        hooks:
        -   id: black
            args:
              - --line-length
              - '119'
              - --target-version
              - py38
    # -   repo: local
    #     hooks:
    #     -   id: test-bigbio
    #         name: running bigbio unit tests
    #         entry: python -m tests.test_bigbio
    #         language: system
    #         pass_filenames: false
    #         always_run: true