from enum import Enum
from types import SimpleNamespace


BigBioValues = SimpleNamespace(NULL="<BB_NULL_STR>")

class Tasks(Enum):
    NAMED_ENTITY_RECOGNITION = "NER"
    NAMED_ENTITY_DISAMBIGUATION = "NED"
    EVENT_EXTRACTION = "EE"
    RELATION_EXTRACTION = "RE"
    COREFERENCE_RESOLUTION = "COREF"

    QUESTION_ANSWERING = "QA"

    TEXTUAL_ENTAILMENT = "TE"

    SEMANTIC_SIMILARITY = "STS"

    PARAPHRASING = "PARA"
    TRANSLATION = "TRANSL"
    SUMMARIZATION = "SUM"

    TEXT_CLASSIFICATION = "TXTCLASS"
